[package]
name = "futuresdr-audio"
version = "0.0.1"
edition = "2018"

[[bin]]
name = "loopback"
path = "loopback.rs"

[[bin]]
name = "play-file"
path = "play_file.rs"

[[bin]]
name = "play-tone"
path = "play_tone.rs"

[dependencies]
anyhow = "1.0.38"
futuresdr = { path = "../..", features = ["audio"] }
