[package]
name = "buffer_rand"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "4", features = ["derive"] }
futuresdr = { path = "../..", features = ["flow_scheduler"] }
tracing = { version = "0.1", features = ["release_max_level_off"] }

[[bin]]
name = "buffer_rand"
path = "buffer_rand.rs"
