[package]
name = "vulkan"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "4", features = ["derive"] }
futuresdr = { path = "../..", features = ["vulkan"] }
rand = "0.8"
tracing = { version = "0.1", features = ["release_max_level_off"] }

[[bin]]
name = "vulkan"
path = "vulkan.rs"
