[package]
name = "lora"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
futuresdr = { path = "../..", features = ["seify"] }
rustfft = "6.1.0"
ordered-float = "3.9.1"
