[package]
name = "rx-to-file"
version = "0.1.0"
edition = "2021"

[dependencies]
futuresdr = { path = "../..", features = ["soapy"] }
num-complex = "0.4.0"
clap = { version = "3.0.13", features = ["derive"] }
