[package]
name = "fir"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.34"
futuresdr = { path = "../..", features = ["flow_scheduler", "tpb_scheduler"] }
rand = "0.8.0"

[[bin]]
name = "fir"
path = "fir.rs"
