use crate::prelude::*;
use std::collections::VecDeque;

/// Split bursts up into multiple smaller bursts by rewriting and adding "burst_start" tags.
/// dos not change the samples themselves, and assumes the sum of the new burst lengths generated by the supplied function matches the original burst length.
///
/// # Stream Inputs
///
/// `in`: Input, expected to contain "burst_start" named_usize tags
///
/// # Stream Outputs
///
/// `out`: Output, exact copy of the input samples with changed and added "burst_start" tags so as to split each input burst into one or multiple new bursts
///
/// # Usage
/// ```rust
/// use futuresdr::blocks::{BurstPad, BurstSplit, BurstSizeRewriter};
/// // use futuresdr::blocks::seify::Builder;
/// use futuresdr::prelude::*;
/// /// produces a single tagged burst of 8 zeroes
/// #[derive(Block)]
/// struct DummyBurstSource<
///     O = DefaultCpuWriter<Complex32>,
/// >
/// where
///     O: CpuBufferWriter<Item = Complex32>,
/// {
///     #[output]
///     output: O,
/// }
/// impl<O> DummyBurstSource<O>
/// where
///     O: CpuBufferWriter<Item = Complex32>,
/// {
///     pub fn new() -> Self {
///         let mut out = O::default();
///         out.set_min_items(8);
///         Self{
///             output: out,
///         }
///     }
/// }
/// impl<O> Kernel for DummyBurstSource<O>
/// where
///     O: CpuBufferWriter<Item = Complex32>,
/// {
///     async fn work(
///         &mut self,
///         io: &mut WorkIo,
///         _m: &mut MessageOutputs,
///         _b: &mut BlockMeta,
///     ) -> Result<()> {
///         let (out, mut out_tags) = self.output.slice_with_tags();
///         if out.len() >= 8 {
///             out[..8].fill(Complex32::new(0.0, 0.0));
///             out_tags.add_tag(0, Tag::NamedUsize("burst_start".to_string(), 8));
///             self.output.produce(8);
///             io.finished = true;
///         }
///         Ok(())
///     }
/// }
/// // example pipeline to enable burst transmissions with the HackRF One in Half-Duplex mode:
/// // first, extend each burst for individual lossless transmission, as the hackrf might discard queued samples when switching back to receive mode
/// // then, pad the bursts to multiples of the hackrf transmit buffer size to ensure immediate transmission without the sink waiting to fill the buffer first
/// // finally, break long bursts up into sub-bursts no longer than the hackrf transmit buffer size, as longer burst transmissions are currently not supported by the driver.
/// // Overall, this ensures immediate and lossless transmission of bursts. While there is a chance for buffer underflow corrupting frames due to the chunking in the last step, this is very small, as the previous padding and a sufficiently sized buffer at the sink ensure that the required amount of samples to finish the original burst shoud be pretty much immediately available.
/// fn main() -> Result<()> {
///     // get a sample stream that contains "burst_start" tags
///     let source: DummyBurstSource = DummyBurstSource::new();
///     // keep track of the maximum expected burst size
///     let mut max_burst_size: usize = 8;
///     // pad each individual burst (there is only one in this example) to ensure lossless transmission with the HackRF One in Half-Duplex mode
///     let pad_head: BurstPad = BurstPad::new_for_hackrf();
///     // keep track of the maximum expected burst size
///     max_burst_size = pad_head.propagate_max_burst_size(max_burst_size);
///     // pad each burst by a given function over its original length, in this case to a multiple of the HackRF transmit buffer size
///     let pad: BurstSizeRewriter = BurstSizeRewriter::new_for_hackrf();
///     // keep track of the maximum expected burst size
///     max_burst_size = pad.propagate_max_burst_size(max_burst_size);
///     // split each burst into mutliple sub-bursts, here specifically for the HackRF One, which can only transmit bursts with a fixed/maximum size
///     let split_bursts: BurstSplit = BurstSplit::new_for_hackrf();
///     // keep track of the maximum expected burst size
///     max_burst_size = split_bursts.propagate_max_burst_size(max_burst_size);
///     // create sink with sufficiently sized input buffer to not stall on large bursts
///     // let sink = Builder::new("driver=soapy,soapy_driver=hackrf")?
///     //        .min_in_buffer_size(max_burst_size) // make sure the sink won't deadlock on large bursts due to insufficient buffer size
///     //        .build_sink()?;
///     // [connect and run Flowgraph]
///     Ok(())
/// }
/// ```
#[derive(Block)]
pub struct BurstSplit<
    T: Copy + Send + 'static = Complex32,
    I = DefaultCpuReader<T>,
    O = DefaultCpuWriter<T>,
> where
    I: CpuBufferReader<Item = T>,
    O: CpuBufferWriter<Item = T>,
{
    #[input]
    input: I,
    #[output]
    output: O,
    samples_remaining_in_current_burst: usize,
    current_remaining_sub_burst_lengths: Option<VecDeque<usize>>,
    current_sub_burst_tag_pending: bool,
    /// generate the new sub-burst lengths from the original burst size. Sum of output list must match input value.
    burst_size_function: fn(usize) -> VecDeque<usize>,
    _type: std::marker::PhantomData<T>,
}

impl<T: Copy + Send + 'static, I, O> BurstSplit<T, I, O>
where
    I: CpuBufferReader<Item = T>,
    O: CpuBufferWriter<Item = T>,
{
    /// Create [`struct@BurstSizeRewriter`] block
    pub fn new(burst_size_function: fn(usize) -> VecDeque<usize>) -> Self {
        BurstSplit::<T, I, O> {
            input: I::default(),
            output: O::default(),
            samples_remaining_in_current_burst: 0,
            current_remaining_sub_burst_lengths: None,
            current_sub_burst_tag_pending: false,
            burst_size_function,
            _type: std::marker::PhantomData,
        }
    }

    /// compute the maximum produced burst length based on the maximum expected input sample burst.
    /// useful for correctly sizing the input buffer of a burst-aware downstream sink to avoid deadlocks, as it needs to wait for the whole burst to be available before starting to precess it.
    pub fn propagate_max_burst_size(&self, max_input_burst_size: usize) -> usize {
        *(self.burst_size_function)(max_input_burst_size)
            .iter()
            .max()
            .unwrap()
    }
}

#[doc(hidden)]
impl<T: Copy + Send + 'static, I, O> Kernel for BurstSplit<T, I, O>
where
    I: CpuBufferReader<Item = T>,
    O: CpuBufferWriter<Item = T>,
{
    async fn work(
        &mut self,
        io: &mut WorkIo,
        _m: &mut MessageOutputs,
        _b: &mut BlockMeta,
    ) -> Result<()> {
        let mut consumed = 0;
        let mut produced = 0;

        let (i, i_tags) = self.input.slice_with_tags();
        let (o, mut o_tags) = self.output.slice_with_tags();
        let num_samples_in_input = i.len();
        let num_slots_in_output = o.len();

        'outer: loop {
            if self.samples_remaining_in_current_burst > 0 {
                if let Some(mut output_len_remaining) =
                    self.current_remaining_sub_burst_lengths.take()
                {
                    // copy and tag next sub-burst
                    let n_copy = (num_samples_in_input - consumed)
                        .min(num_slots_in_output - produced)
                        .min(output_len_remaining[0]);
                    if n_copy > 0 {
                        if self.current_sub_burst_tag_pending {
                            // tag the new sub-burst
                            o_tags.add_tag(
                                produced,
                                Tag::NamedUsize("burst_start".to_string(), output_len_remaining[0]),
                            );
                            self.current_sub_burst_tag_pending = false;
                        }
                        o[produced..produced + n_copy]
                            .copy_from_slice(&i[consumed..consumed + n_copy]);
                        consumed += n_copy;
                        produced += n_copy;
                        output_len_remaining[0] -= n_copy;
                        self.samples_remaining_in_current_burst -= n_copy;
                        if output_len_remaining[0] == 0 {
                            output_len_remaining.pop_front();
                            self.current_sub_burst_tag_pending = true;
                            if output_len_remaining.is_empty() {
                                debug_assert_eq!(self.samples_remaining_in_current_burst, 0);
                                continue 'outer;
                            }
                        }
                        self.current_remaining_sub_burst_lengths = Some(output_len_remaining);
                    } else {
                        self.current_remaining_sub_burst_lengths = Some(output_len_remaining);
                        break 'outer;
                    }
                } else {
                    let n_copy = (num_samples_in_input - consumed)
                        .min(num_slots_in_output - produced)
                        .min(self.samples_remaining_in_current_burst);
                    // TODO this just copies
                    o[produced..produced + n_copy].copy_from_slice(&i[consumed..consumed + n_copy]);
                    consumed += n_copy;
                    produced += n_copy;
                    self.samples_remaining_in_current_burst -= n_copy;
                }
            } else {
                // get new state depending on available input
                if num_samples_in_input - consumed == 0 {
                    break 'outer;
                } else {
                    (self.samples_remaining_in_current_burst, self.current_remaining_sub_burst_lengths) = i_tags
                        .iter()
                        .find_map(|x| match x {
                            ItemTag {
                                index,
                                tag: Tag::NamedUsize(n, len),
                            } => {
                                if n == "burst_start" {
                                    if *index < consumed {
                                        warn!("dropping missed Tag: Tag::NamedUsize({n}, {len}) @ index {index}.");
                                        None
                                    } else if *index == consumed {
                                        debug_assert_ne!(*len, 0);
                                        self.current_sub_burst_tag_pending = true;
                                        Some((
                                            *len,
                                            Some((self.burst_size_function)(*len))
                                        ))
                                    } else {
                                        // burst starting later, consume samples until then as non-tagged
                                        Some((
                                            *index - consumed,
                                            None
                                        ))
                                    }
                                } else {
                                    None
                                }
                            }
                            _ => None,
                        })
                        .unwrap_or((
                            num_samples_in_input - consumed,
                            None
                        ));
                }
            }
        }

        if consumed > 0 {
            // debug!("consumed {consumed} samples");
            self.input.consume(consumed);
        }
        if produced > 0 {
            // debug!("produced {produced} samples");
            self.output.produce(produced);
        }

        if self.input.finished() && consumed == num_samples_in_input {
            io.finished = true;
        }

        Ok(())
    }
}
