[package]
name = "null_rand_latency"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.1"
futuresdr = { path = "../..", features = ["flow_scheduler", "tpb_scheduler"] }
lttng-ust = "0.1.0"

[build-dependencies]
lttng-ust-generate = "0.1.1"

[[bin]]
name = "null_rand_latency"
path = "null_rand_latency.rs"
