[package]
name = "null_rand_latency"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.1"
futuresdr = { path = "../..", features = ["flow_scheduler", "tpb_scheduler", "lttng"] }

[[bin]]
name = "null_rand_latency"
path = "null_rand_latency.rs"
