[package]
name = "null_rand"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.38"
clap = "2.33.1"
futuresdr = { path = "../..", default-features = false }

[[bin]]
name = "null_rand"
path = "null_rand.rs"
