[package]
name = "sync"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1.0"
futuresdr = { path = "../..", features = ["flow_scheduler"] }
rand = "0.8.0"

[[bin]]
name = "sync"
path = "sync.rs"
